training_pipeline_config:
  pipeline_name : back_order   # artifact store in this file
  artifact_dir : artifact


data_ingestion_config:
  dataset_download_url : https://raw.githubusercontent.com/ratankj/DATASET/main/backorder.csv
  raw_data_dir : raw_data
  ingested_dir: ingested_data
  ingested_train_dir : train
  ingested_test_dir : test

